on:
  workflow_dispatch:
    tags:
      - v*
  push:
    tags:
      - v*

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
